In [125]:
# Basic Libraries
import numpy as np
import pandas as pd
import seaborn as sb
import matplotlib.pyplot as plt # we only need pyplot
sb.set() # set the default Seaborn style for graphics

In [126]:
full_dataframe = pd.read_csv("churn.csv", index_col=0, parse_dates=True)
full_dataframe

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
#,,,,,,,,,,,,,,,,,,,,,
1,2967-MXRAV,Male,0,Yes,Yes,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,18.80,18.8,No
2,8992-CEUEN,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Electronic check,18.85,18.85,No
3,9318-NKNFC,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,18.85,18.85,Yes
4,9975-SKRNR,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,18.90,18.9,No
5,1423-BMPBQ,Female,0,Yes,Yes,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.00,19,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7039,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
7040,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
7041,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No
7042,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No
7043,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No

# This is a combined dataset which will consist of Train & Evaluation (80%) and Test (20%) from the 7043 rows. We will be cleaning it before creating a train and test dataframe.

In [127]:
print("Data type : ", type(full_dataframe))
print("Data dims : ", full_dataframe.shape)
full_dataframe.info()

Data type :  <class 'pandas.core.frame.DataFrame'>
Data dims :  (7043, 21)
<class 'pandas.core.frame.DataFrame'>
Int64Index: 7043 entries, 1 to 7043
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

# Checking if the dataset have null values

In [128]:
full_dataframe.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

# No internet service will be classified as No in other columns like in MultipleLines, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV and StreamingMovies

In [129]:
full_dataframe.loc[full_dataframe["OnlineSecurity"] == "No internet service"]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
#,,,,,,,,,,,,,,,,,,,,,
1,2967-MXRAV,Male,0,Yes,Yes,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,No,Mailed check,18.80,18.8,No
2,8992-CEUEN,Female,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Electronic check,18.85,18.85,No
3,9318-NKNFC,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,18.85,18.85,Yes
4,9975-SKRNR,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,18.90,18.9,No
5,1423-BMPBQ,Female,0,Yes,Yes,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Mailed check,19.00,19,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7036,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
7038,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No
7039,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No
7040,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No
7041,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No

In [130]:
full_dataframe["MultipleLines"].replace("No phone service","No",inplace=True)

In [131]:
full_dataframe["OnlineSecurity"].replace("No internet service","No",inplace=True)

In [132]:
full_dataframe["OnlineBackup"].replace("No internet service","No",inplace=True)

In [133]:
full_dataframe["DeviceProtection"].replace("No internet service","No",inplace=True)

In [134]:
full_dataframe["TechSupport"].replace("No internet service","No",inplace=True)

In [135]:
full_dataframe["StreamingTV"].replace("No internet service","No",inplace=True)

In [136]:
full_dataframe["StreamingMovies"].replace("No internet service","No",inplace=True)

# Filtering Data to see if column is cleaned

In [137]:
# MultipleLines       0
# OnlineSecurity      0
# OnlineBackup        0
# DeviceProtection    0
# TechSupport         0
# StreamingTV         0
# StreamingMovies     0

full_dataframe.loc[full_dataframe["OnlineSecurity"] == "No internet service"]

Empty DataFrame
Columns: [customerID, gender, SeniorCitizen, Partner, Dependents, tenure, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, MonthlyCharges, TotalCharges, Churn]
Index: []

[0 rows x 21 columns]

# Label Encoding as our pre-processing of data to change Yes and No data into 1 and 0 before we can use it to manipulate our data.

In [140]:
 #3   Partner           7043 non-null   object 
 #4   Dependents        7043 non-null   object 
 #6   PhoneService      7043 non-null   object 
 #7   MultipleLines     7043 non-null   object 
 #8   InternetService   7043 non-null   object 
 #9   OnlineSecurity    7043 non-null   object 
 #10  OnlineBackup      7043 non-null   object 
 #11  DeviceProtection  7043 non-null   object 
 #12  TechSupport       7043 non-null   object 
 #13  StreamingTV       7043 non-null   object 
 #14  StreamingMovies   7043 non-null   object 
 #16  PaperlessBilling  7043 non-null   object

In [146]:
from sklearn.preprocessing import LabelEncoder

In [153]:
pd.get_dummies(full_dataframe, columns=["Partner"]).head()

,customerID,gender,SeniorCitizen,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Partner_No,Partner_Yes
#,,,,,,,,,,,,,,,,,,,,,
1,2967-MXRAV,Male,0,Yes,1,Yes,No,No,No,No,...,No,No,One year,No,Mailed check,18.80,18.8,False,0,1
2,8992-CEUEN,Female,0,No,1,Yes,No,No,No,No,...,No,No,Month-to-month,No,Electronic check,18.85,18.85,False,1,0
3,9318-NKNFC,Male,0,No,1,Yes,No,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,18.85,18.85,True,1,0
4,9975-SKRNR,Male,0,No,1,Yes,No,No,No,No,...,No,No,Month-to-month,No,Mailed check,18.90,18.9,False,1,0
5,1423-BMPBQ,Female,0,Yes,1,Yes,No,No,No,No,...,No,No,Month-to-month,Yes,Mailed check,19.00,19,False,0,1

# One Hot Encoding on Contract and Payment Method

In [163]:
pd.get_dummies(full_dataframe, columns=["Contract"]).head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Contract_Month-to-month,Contract_One year,Contract_Two year
#,,,,,,,,,,,,,,,,,,,,,
1,2967-MXRAV,Male,0,Yes,Yes,1,Yes,No,No,No,...,No,No,No,Mailed check,18.80,18.8,False,0,1,0
2,8992-CEUEN,Female,0,No,No,1,Yes,No,No,No,...,No,No,No,Electronic check,18.85,18.85,False,1,0,0
3,9318-NKNFC,Male,0,No,No,1,Yes,No,No,No,...,No,No,Yes,Mailed check,18.85,18.85,True,1,0,0
4,9975-SKRNR,Male,0,No,No,1,Yes,No,No,No,...,No,No,No,Mailed check,18.90,18.9,False,1,0,0
5,1423-BMPBQ,Female,0,Yes,Yes,1,Yes,No,No,No,...,No,No,Yes,Mailed check,19.00,19,False,1,0,0

In [164]:
pd.get_dummies(full_dataframe, columns=["PaymentMethod"]).head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,PaymentMethod_Bank transfer (automatic),PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
#,,,,,,,,,,,,,,,,,,,,,
1,2967-MXRAV,Male,0,Yes,Yes,1,Yes,No,No,No,...,No,One year,No,18.80,18.8,False,0,0,0,1
2,8992-CEUEN,Female,0,No,No,1,Yes,No,No,No,...,No,Month-to-month,No,18.85,18.85,False,0,0,1,0
3,9318-NKNFC,Male,0,No,No,1,Yes,No,No,No,...,No,Month-to-month,Yes,18.85,18.85,True,0,0,0,1
4,9975-SKRNR,Male,0,No,No,1,Yes,No,No,No,...,No,Month-to-month,No,18.90,18.9,False,0,0,0,1
5,1423-BMPBQ,Female,0,Yes,Yes,1,Yes,No,No,No,...,No,Month-to-month,Yes,19.00,19,False,0,0,0,1

# Splitting of Data into Train and Test dataframe

In [159]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(full_dataframe, test_size=0.2)

# 5634 Rows of data in our Train Dataframe randomly

In [160]:
train

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
#,,,,,,,,,,,,,,,,,,,,,
2446,2384-OVPSA,Female,1,No,No,38,Yes,No,No,No,...,No,No,No,No,Two year,No,Mailed check,20.20,735.9,False
4919,5373-SFODM,Male,1,Yes,No,36,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Credit card (automatic),85.25,3132.75,True
5696,7501-IWUNG,Female,0,Yes,Yes,61,Yes,No,DSL,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),73.80,4616.05,False
4973,5135-RDDQL,Female,0,Yes,Yes,63,Yes,No,DSL,Yes,...,No,No,No,No,Two year,Yes,Bank transfer (automatic),50.65,3221.25,False
3094,4338-EYCER,Male,0,Yes,No,21,Yes,No,DSL,No,...,No,No,Yes,No,Month-to-month,No,Bank transfer (automatic),54.60,1125.2,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2586,6969-MVBAI,Female,1,No,No,9,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,No,Month-to-month,Yes,Electronic check,90.10,816.8,False
5476,8178-EYZUO,Male,0,No,No,46,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,93.70,4154.8,True
57,6849-WLEYG,Male,0,No,Yes,1,Yes,No,No,No,...,No,No,No,No,Month-to-month,No,Mailed check,19.75,19.75,True
6330,9530-GRMJG,Male,0,Yes,Yes,70,Yes,Yes,DSL,No,...,Yes,Yes,Yes,Yes,Two year,Yes,Electronic check,84.10,5979.7,False
5800,8945-MUQUF,Male,0,No,No,51,Yes,Yes,Fiber optic,Yes,...,No,No,Yes,No,One year,Yes,Electronic check,94.80,4837.6,True

# 1409 Rows of data in our Test Dataframe randomly

In [161]:
test

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
#,,,,,,,,,,,,,,,,,,,,,
5552,9253-VIFJQ,Male,0,Yes,No,65,Yes,Yes,DSL,Yes,...,Yes,No,No,No,One year,No,Credit card (automatic),67.05,4309.55,False
89,7096-UCLNH,Male,0,No,No,1,Yes,No,No,No,...,No,No,No,No,Month-to-month,No,Mailed check,20.05,20.05,False
5315,4879-GZLFH,Female,0,Yes,Yes,42,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,92.15,3875.4,False
275,6982-SSHFK,Male,0,No,No,1,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,44.40,44.4,True
6729,3761-FLYZI,Female,1,Yes,No,65,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),108.80,7082.45,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1474,3049-SOLAY,Female,0,Yes,No,3,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,95.20,292.85,True
1510,6705-LXORM,Female,1,Yes,No,5,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,No,Electronic check,70.05,302.6,False
5854,2267-FPIMA,Male,0,Yes,No,50,Yes,Yes,Fiber optic,Yes,...,No,No,No,Yes,Month-to-month,Yes,Credit card (automatic),94.40,4914.9,False
3755,8245-UMPYT,Female,1,No,No,16,Yes,Yes,Fiber optic,No,...,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,96.40,1581.2,True
5698,4075-JFPGR,Female,0,Yes,No,51,Yes,No,Fiber optic,Yes,...,Yes,No,Yes,No,One year,Yes,Electronic check,93.50,4619.55,False

# Finding The Highest Corr to Churn

train.corr()

# KFold Cross Validation

In [112]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [121]:
tcharge = pd.DataFrame(train['TotalCharges'])   # Response
tchurn = pd.DataFrame(train['Churn'])       # Predictor

In [122]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(tcharge, tchurn, test_size = 0.20)

# Logistic Regression

In [ ]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

# Support Vector Machine (SVM)

In [ ]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

# Random Forest

In [ ]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

# KFold cross validation

In [ ]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

In [ ]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

In [ ]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [ ]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [ ]:
scores_logistic

In [ ]:
scores_svm

In [ ]:
scores_rf

# cross_val_score function

In [ ]:
from sklearn.model_selection import cross_val_score

# Logistic regression model performance using cross_val_score

In [ ]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

# svm model performance using cross_val_score

In [ ]:
cross_val_score(SVC(gamma='auto'), digits.data, digits.target,cv=3)

# random forest performance using cross_val_score

In [ ]:
cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target,cv=3)

# Parameter tunning using k fold cross validation

In [ ]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

In [ ]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

In [ ]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

In [ ]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)